# Case Study #1: Danny's Diner

Original case study and questions: https://8weeksqlchallenge.com/case-study-1/ (by Danny Ma)

Danny's restaurant sells sushi, curry and ramen. Three tables: `sales`, `menu`, `members`.
This notebook holds my queries and notes.

%pip install psycopg2-binary

## Setup

This cell builds the three tables from `schema.sql` and defines `q()`, a shortcut for running SQL and showing the result as a table.
Initially set as sqlite3 , changed to postgres

import sqlite3
import pandas as pd

con = sqlite3.connect("dannys_diner.db")
con.executescript(open("schema.sql").read())   # builds the 3 tables

def q(sql):
    return pd.read_sql(sql, con)

In [48]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://carolkarimi@localhost:5432/dannys_diner")

def q(sql):
    return pd.read_sql(text(sql), engine)

## Warm-up: simple SELECTs

**Show all tables**

In [52]:
sales=q("SELECT * FROM sales")
sales

   customer_id  order_date  product_id
0            A  2021-01-01           1
1            A  2021-01-01           2
2            A  2021-01-07           2
3            A  2021-01-10           3
4            A  2021-01-11           3
5            A  2021-01-11           3
6            B  2021-01-01           2
7            B  2021-01-02           2
8            B  2021-01-04           1
9            B  2021-01-11           1
10           B  2021-01-16           3
11           B  2021-02-01           3
12           C  2021-01-01           3
13           C  2021-01-01           3
14           C  2021-01-07           3

In [54]:
menu=q("SELECT * FROM menu")
menu

   product_id product_name  price
0           1        sushi     10
1           2        curry     15
2           3        ramen     12

In [56]:
members=q("select * FROM members")
members

  customer_id   join_date
0           A  2021-01-07
1           B  2021-01-09

## Question 1

**Question:** What is the total amount each customer spent at the restaurant?

**Approach:** Join sales to menu to get each item's price, then sum per customer.

In [59]:
q("""
SELECT customer_id,sum(price) AS total_spent 
FROM sales 
LEFT JOIN menu ON sales.product_id=menu.product_id
GROUP BY customer_id
ORDER BY customer_id 
""")

  customer_id  total_spent
0           A           76
1           B           74
2           C           36

## Question 2

**Question:** How many days has each customer visited the restaurant?

**Approach:** use groupby to count distinct days drom sales

In [64]:
sales

   customer_id  order_date  product_id
0            A  2021-01-01           1
1            A  2021-01-01           2
2            A  2021-01-07           2
3            A  2021-01-10           3
4            A  2021-01-11           3
5            A  2021-01-11           3
6            B  2021-01-01           2
7            B  2021-01-02           2
8            B  2021-01-04           1
9            B  2021-01-11           1
10           B  2021-01-16           3
11           B  2021-02-01           3
12           C  2021-01-01           3
13           C  2021-01-01           3
14           C  2021-01-07           3

In [84]:
q("""
SELECT  customer_id,COUNT(DISTINCT(order_date)) AS days_visited
FROM sales GROUP BY customer_id
""")

  customer_id  days_visited
0           A             4
1           B             6
2           C             2

## Question 3

**Question:** What was the first item from the menu purchased by each customer?

**Approach:**

## Question 4

**Question:** What is the most purchased item on the menu and how many times was it purchased by all customers?

**Approach:**

## Question 5

**Question:** Which item was the most popular for each customer?

**Approach:**

## Question 6

**Question:** Which item was purchased first by the customer after they became a member?

**Approach:**

## Question 7

**Question:** Which item was purchased just before the customer became a member?

**Approach:**

## Question 8

**Question:** What is the total items and amount spent for each member before they became a member?

**Approach:**

## Question 9

**Question:** If each $1 spent equates to 10 points and sushi has a 2x points multiplier - how many points would each customer have?

**Approach:**

## Question 10

**Question:** In the first week after a customer joins the program (including their join date) they earn
2x points on all items, not just sushi - how many points do customer A and B have at the end of January?

**Approach:**